# Generated by Django 5.0.14 on 2026-07-17 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "nature",
                    models.CharField(
                        choices=[("REVENU", "Revenu"), ("DEPENSE", "Dépense")],
                        max_length=10,
                        verbose_name="nature",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sous_categories",
                        to="finances.category",
                        verbose_name="catégorie parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "ordering": ["nature", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[("REVENU", "Revenu"), ("DEPENSE", "Dépense")],
                        max_length=10,
                        verbose_name="type d'opération",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="montant",
                    ),
                ),
                (
                    "date_operation",
                    models.DateField(db_index=True, verbose_name="date de l'opération"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finances.category",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="centres.centre",
                        verbose_name="centre",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_saisies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="saisi par",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "ordering": ["-date_operation", "-date_creation"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("nom", "nature", "parent"), name="unique_categorie"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["centre", "date_operation"],
                name="finances_tr_centre__d94264_idx",
            ),
        ),
    ]
