# Generated by Django 5.0.14 on 2026-07-17 20:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="montant",
            ),
        ),
    ]
