# Generated by Django 5.0.14 on 2026-07-18 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centres", "0001_initial"),
        ("finances", "0002_alter_transaction_montant"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_categorie",
        ),
        migrations.AddField(
            model_name="category",
            name="centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="centres.centre",
                verbose_name="centre",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("nom", "nature", "parent", "centre"), name="unique_categorie"
            ),
        ),
    ]
