# Generated by Django 5.0.14 on 2026-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_tiers_et_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
    ]
