# Generated by Django 5.0.14 on 2026-07-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                ("libelle", models.CharField(max_length=150, verbose_name="libellé")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "type de centre",
                "verbose_name_plural": "types de centre",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Centre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "econome_principal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="centre_dirige",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="économe principal",
                    ),
                ),
                (
                    "type_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="centres",
                        to="centres.typecentre",
                        verbose_name="type de centre",
                    ),
                ),
            ],
            options={
                "verbose_name": "centre",
                "ordering": ["nom"],
            },
        ),
    ]
