# Generated by Django 5.0.14 on 2026-08-13 11:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centres", "0001_initial"),
        ("finances", "0005_alter_transaction_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypePlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                ("libelle", models.CharField(max_length=150, verbose_name="libellé")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "type de placement",
                "verbose_name_plural": "types de placement",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "niveau_risque",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MODERE", "Modéré"),
                            ("ELEVE", "Élevé"),
                        ],
                        max_length=10,
                        verbose_name="niveau de risque",
                    ),
                ),
                (
                    "montant_investi",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="montant investi",
                    ),
                ),
                (
                    "date_acquisition",
                    models.DateField(verbose_name="date d'acquisition"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_COURS", "En cours"), ("CLOTURE", "Clôturé")],
                        default="EN_COURS",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_cloture",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de clôture"
                    ),
                ),
                (
                    "montant_recupere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="montant récupéré",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "placement",
                "ordering": ["-date_acquisition"],
            },
        ),
        migrations.CreateModel(
            name="MouvementTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("VIREMENT_ENTRANT", "Virement entrant (depuis un centre)"),
                            ("VIREMENT_SORTANT", "Virement sortant (vers un centre)"),
                            ("ACHAT_PLACEMENT", "Achat de placement"),
                            ("RACHAT_PLACEMENT", "Rachat de placement"),
                        ],
                        max_length=20,
                        verbose_name="type de mouvement",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="montant",
                    ),
                ),
                ("date_mouvement", models.DateField(verbose_name="date du mouvement")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné uniquement pour les virements entrants/sortants.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_tresorerie",
                        to="centres.centre",
                        verbose_name="centre",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_tresorerie_saisis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="saisi par",
                    ),
                ),
                (
                    "transaction_liee",
                    models.OneToOneField(
                        blank=True,
                        help_text="Transaction générée côté centre pour un virement.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvement_tresorerie",
                        to="finances.transaction",
                        verbose_name="transaction liée",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné uniquement pour les achats/rachats de placement.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_tresorerie",
                        to="placements.placement",
                        verbose_name="placement",
                    ),
                ),
            ],
            options={
                "verbose_name": "mouvement de trésorerie",
                "ordering": ["-date_mouvement", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Portefeuille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portefeuilles_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "portefeuille",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="placement",
            name="portefeuille",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="placements.portefeuille",
                verbose_name="portefeuille",
            ),
        ),
        migrations.AddField(
            model_name="placement",
            name="type_placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="placements.typeplacement",
                verbose_name="type de placement",
            ),
        ),
        migrations.CreateModel(
            name="ValorisationPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_valorisation",
                    models.DateField(verbose_name="date de valorisation"),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="valeur",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valorisations",
                        to="placements.placement",
                        verbose_name="placement",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valorisations_saisies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="saisi par",
                    ),
                ),
            ],
            options={
                "verbose_name": "valorisation de placement",
                "ordering": ["-date_valorisation"],
            },
        ),
        migrations.AddConstraint(
            model_name="valorisationplacement",
            constraint=models.UniqueConstraint(
                fields=("placement", "date_valorisation"),
                name="unique_valorisation_par_jour",
            ),
        ),
    ]
