# Generated by Django 5.0.14 on 2026-07-17 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("centres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membres",
                to="centres.centre",
                verbose_name="centre",
            ),
        ),
    ]
