# Generated by Django 5.0.14 on 2026-07-17 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationJournaliere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DECLARE_AVEC_MOUVEMENT", "Déclaré avec mouvement"),
                            ("DECLARE_SANS_MOUVEMENT", "Déclaré sans mouvement"),
                        ],
                        max_length=30,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_declaration",
                    models.DateTimeField(auto_now=True, verbose_name="déclaré le"),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to="centres.centre",
                        verbose_name="centre",
                    ),
                ),
                (
                    "declare_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="declarations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="déclaré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "déclaration journalière",
                "verbose_name_plural": "déclarations journalières",
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="declarationjournaliere",
            constraint=models.UniqueConstraint(
                fields=("centre", "date"), name="unique_declaration_par_jour"
            ),
        ),
    ]
